# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  displayName: 'Use Node 8.x'
  inputs:
    versionSpec: 8.x

- task: Npm@1
  displayName: 'npm install'

- task: Npm@1
  displayName: 'Compile'
  inputs:
    command: custom
    customCommand: run compile

- task: Npm@1
  displayName: 'Test'
  inputs:
    command: custom
    customCommand: test
